version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./frontend/dist:/app/frontend/dist
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app/backend
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
